### PR TITLE
Improvements to table section and simplify mention of mixin columns

### PR DESCRIPTION
**Pull request by astrofrog**
Should probably be reviewed by @taldcroft or @mhvk

### CODE REVIEW

**Review by hamogu — APPROVED** [review]
I think the new wording a a lot better for non-experts - the people who we are presumably writing for. In my mind, the docs can assume familiarity with Python (what is an object?), and ApJ sadly allows anyone to subscribe without a basic text of Python proficiency required...

**Comment by hamogu** [comment]
Oh, and while I'd like @mhvk s comments on this, I don't think that in the context of the paper a sign-of of the subpackage maintainer is absolutely required if he does not have time to do it.

**Comment by mhvk** [comment]
@astrofrog - this looks good as a general description. The main question is whether we should make explicit the distinction between`Table` and `QTable`, which treat quantities differently.

**Comment by hamogu** [comment]
Personally, I don't think the `QTable` and `Table` need to be explicitly discussed. Both of them use quantities in some way. There are API differences, but the point is that we have a (one or two) data structures for tabluar data with some extra quirks. I think that docs are better place to make that distinction. I think it's better to focus the paper on the really big picture (how we develop, how we build community, how important testing is for us) and I'm suspect every time we mention names of classes or functions explicitly - but I'm only one person and can be convinced.

**Comment by mhvk** [comment]
I would agree if I didn't think that people really should start using `QTable`, since the units of `Column` get ignored in too many cases; it very much breaks what I see as one of the nicest things in astropy...

One can also see it as an example of how we try to ensure backwards compatibility.

**Comment by bsipocz** [comment]
@astrofrog - This now needs a rebase.

**Comment by crawfordsm** [comment]
Okay, I tried using the online conflict resolution but that didn't seem to work -- but apparently just needed time to update.   Okay will merge now.

**Pull request merged**
