### PR TITLE
Added script to make WCSAxes plot

### PR DESCRIPTION
**Pull request by astrofrog**
I just realized I had never added the script to make the WCSAxes plot. However, the data is 350Mb. Has anyone used git lfs, and is there a way to add the data to this repo using that?

### CODE REVIEW

**Comment by astrofrog** [comment]
Also, do we want to coordinate the plots so that they all have a similar style? (could be done post-submission)

**Comment by bsipocz** [comment]
Isn't the idea in #93 was to merge the two figure into one?

**Comment by bsipocz** [comment]
(It wasn't said anywhere, but since wcsaxes was used there, that was my impression)

**Comment by adrn** [comment]
I've been trying to use the astropy style - I'd suggest we use that for all plots.

For #93, it's just to improve the Lupton RGB image. But yea, we could combine if we wanted since it does use the wcsaxes machinery

**Comment by adrn** [comment]
@astrofrog what to you think about the question of removing this figure, since WCS axes is demoed in the RGB figure now? That is kind of an all-in-one astropy.visualization figure now. (but let's not act on that until after submission)

**Comment by crawfordsm** [comment]
I'm merging this as the script represents the image currently in the paper and will open another issue raised by the comments here.

**Pull request merged**
