### PR TITLE
[tab:coordinate_benchmark] - Modified the order of the comparison of the different packages

### PR DESCRIPTION
**Pull request by dpshelio**
The table now is ordered so the packages that have a closer agreement
are shown together. This way I find it easier to find how they cluster
between themselves.

Also, I agree with the comment by @perrygreenfield (#15) and this would
be an example. But I don't know where is preferred to put the code ([available in a gist](https://gist.github.com/dpshelio/650af4784dcb72bbad0b9900511ec6fb)) in this repository.
coordinates-benchmark

### CODE REVIEW

**Comment by dpshelio** [comment]
Here's a [nice video](http://www.youtube.com/watch?v=qHj616-DWqc) of why I would change the order of the table.

**Comment by hamogu** [comment]
You can put the code in the `figures` figures folder of the repro.

**Comment by hamogu** [comment]
And then include the figure (I like it!) in the latex file. We have several other figures already, just look at which directory that use to store the image file.

**Comment by adrn** [comment]
I don't have strong feelings here - maybe @astrofrog should have the final say? On my last read through the paper, I thought that it might be better to remove the exact statistics from the paper and just link to the coordinates benchmark page (www.astropy.org/coordinates-benchmark/summary_matrix.html).

**Comment by hamogu** [comment]
I think we should have some results in in some way. I'm happy with a figure instead of a table, or a simplified table (e.g. only max or only mean values), but there is a lot of value in showing this approach to software testing - in fact that was my main motivation to try to rally people behind writing another paper (which I intended for 1.0, then 1.2, and now it's actually happening for 2.0) and I'm just afraind that without number of any sort in the paper people won't take that seriously.

**Comment by hamogu** [comment]
Thus, I'm merging this in now. IF the referee thinks it's too confusing, we can still simplify it to only show one of four numbers. @astrofrog and I have talked quite a bit what level of detail should be in here, so I'm confident that he'll be OK with this (and if not, open a PR to change it again).

**Pull request merged**
