### PR TITLE
Update to AASTeX v6.2 macros

### PR DESCRIPTION
**Pull request by migueldvb**
New in v6.2, the limit of 100 authors has been fixed and a few other changes:

http://journals.aas.org/authors/aastex/revisionhistory.html

### CODE REVIEW

**Comment by adrn** [comment]
Don't you also have to do: `\documentclass[modern]{aastex62}` in main.tex?

**Comment by migueldvb** [comment]
Oops, I forgot to add the main.tex changes to the commit. It should be there now.

**Comment by crawfordsm** [comment]
@migueldvb was there another commit or is this ready to go?

**Comment by migueldvb** [comment]
I ammended the last commit with the required change in main.tex so it should be good to go.

**Pull request merged**
